meta_product_name: "Mo-Intern"
meta_title: "Mo-Intern - Your internship is one click away"
meta_description: "We are a team of commited young graduates who are helping to connect aspiring job seekers with great employers. We have a history of 15 years. We have had more than 100,000 students using our website to apply for internships."
meta_image: "mo-intern-logo.png" # should exist in `app/assets/images/`
